[project]
name = "jyakoTen"
version = "0.1"
description = "recognized text scoreing library"
requires-python = ">=3.10"
license = {text = "MIT License"}

dependencies =[
"pyopenjtalk",
"alkana",
"mecab-python3",
"unidic_lite",
]
[tool.setuptools]
py-modules = ["utils"]